import os
import json
import logging

from dotenv import load_dotenv
from fastapi import FastAPI, Request
from fastapi.staticfiles import StaticFiles
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel

from formatter import format_transcript
from setup_guide_agent.agent import generate_guide

# Load environment variables
load_dotenv()

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - %(levelname)s - %(message)s",
)
logger = logging.getLogger(__name__)

# ========================================
# Application Initialization
# ========================================

app = FastAPI(title="OpenClaw Concierge")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# In-memory store for generated guides (good enough for hackathon — no database needed)
guide_store: dict[str, dict] = {}

MOCK_SETUP_GUIDE = r"""# OpenClaw Engine Setup Guide
## Personalized for: Alex — Restaurant Chain on Google Cloud

> Generated by EasyClaw AI Concierge based on your voice interview.

---

### 1. Prerequisites

| Requirement | Status |
|-------------|--------|
| Google Cloud account with billing enabled | Required |
| `gcloud` CLI installed (v450+) | Required |
| Node.js 20+ and npm | Required |
| Python 3.11+ | Required |
| A domain name (for OAuth redirect) | Recommended |

---

### 2. Install OpenClaw

```bash
# Install the OpenClaw CLI
npm install -g @openclaw/cli

# Verify installation
openclaw --version
# Expected: openclaw v2.4.x
```

### 3. Google Cloud Project Setup

```bash
# Authenticate with Google Cloud
gcloud auth application-default login

# Set your project
gcloud config set project restaurant-ai-prod

# Enable required APIs
gcloud services enable \
  aiplatform.googleapis.com \
  secretmanager.googleapis.com \
  cloudfunctions.googleapis.com \
  calendar-json.googleapis.com
```

> See `reference_documents/gcp_oauth_setup.md` for the full OAuth consent screen configuration.

### 4. Initialize Your OpenClaw Instance

```bash
# Create a new OpenClaw project
openclaw init --name "RestaurantConcierge" \
  --provider vertex-ai \
  --region us-central1

# This creates:
#   ~/.openclaw/config.yaml
#   ~/.openclaw/skills/
#   ~/.openclaw/knowledge/
```

### 5. Install Recommended Skills

Based on your interview, here are the skills tailored to your restaurant business:

#### Tier 1 — Essential
```bash
clawhub install skill-vetter          # 🛡️ Always install first
clawhub install gog                   # 🟢 Google Workspace (Gmail, Calendar, Drive)
clawhub install summarize             # 🟢 Summarize menus, reviews, reports
clawhub install tavily-web-search     # ⭐ AI-optimized web search
```

#### Tier 2 — Productivity
```bash
clawhub install todoist               # ✅ Task management for daily ops
clawhub install notion                # 🔵 Menu planning & SOPs in Notion
clawhub install google-calendar       # 🟢 Staff scheduling integration
```

#### Tier 3 — Business-Specific
```bash
clawhub install openai-whisper        # 🔵 Transcribe supplier calls
clawhub install csv-tools             # ✅ Inventory spreadsheet analysis
clawhub install slack                 # ✅ Team communication hub
```

### 6. Configure Google OAuth

Your setup requires OAuth for Google Calendar and Gmail access:

```bash
# Set up OAuth credentials
openclaw auth setup google \
  --client-id YOUR_CLIENT_ID \
  --client-secret YOUR_CLIENT_SECRET \
  --redirect-uri https://yourdomain.com/auth/callback \
  --scopes calendar.events,gmail.readonly,drive.readonly
```

> Full step-by-step: See `reference_documents/gcp_oauth_setup.md`

### 7. Knowledge Base Setup

Upload your restaurant-specific knowledge:

```bash
# Add your restaurant's operating procedures
openclaw knowledge add ./sops/ --tag "operations"

# Add menu data
openclaw knowledge add ./menus/ --tag "menu"

# Add supplier contacts
openclaw knowledge add ./suppliers.csv --tag "vendors"
```

### 8. Launch & Verify

```bash
# Start OpenClaw in development mode
openclaw start --dev

# Run the built-in health check
openclaw doctor

# Expected output:
# ✅ Google Cloud authenticated
# ✅ 9 skills installed (0 warnings)
# ✅ Knowledge base: 3 collections, 47 documents
# ✅ Ready to chat!
```

### 9. First Conversation Test

Open your browser to `http://localhost:3000` and try:

> "What's on the lunch menu today and do I have any supplier deliveries scheduled?"

This tests: `gog` (Calendar), knowledge base (menu), and the core reasoning engine.

---

*Guide generated by EasyClaw • Guide ID: demo-0001*
"""

MOCK_REFERENCE_DOCS = [
    {
        "name": "gcp_oauth_setup.md",
        "content": r"""# Google Cloud OAuth Setup — Step by Step

## 1. Create OAuth Consent Screen

1. Go to [Google Cloud Console → APIs & Services → OAuth consent screen](https://console.cloud.google.com/apis/credentials/consent)
2. Select **External** user type
3. Fill in:
   - App name: `RestaurantConcierge`
   - User support email: your email
   - Authorized domains: `yourdomain.com`
4. Add scopes:
   - `https://www.googleapis.com/auth/calendar.events`
   - `https://www.googleapis.com/auth/gmail.readonly`
   - `https://www.googleapis.com/auth/drive.readonly`
5. Add test users (your email)

## 2. Create Credentials

1. Go to **APIs & Services → Credentials**
2. Click **+ CREATE CREDENTIALS → OAuth client ID**
3. Application type: **Web application**
4. Authorized redirect URIs: `https://yourdomain.com/auth/callback`
5. Download the JSON credentials file

## 3. Configure in OpenClaw

```bash
openclaw auth setup google \
  --credentials-file ./client_secret.json \
  --redirect-uri https://yourdomain.com/auth/callback

# Complete the OAuth flow in your browser
openclaw auth verify google
# ✅ Google OAuth configured successfully
```

## Troubleshooting

| Issue | Fix |
|-------|-----|
| `redirect_uri_mismatch` | Ensure the redirect URI in Cloud Console exactly matches your config |
| `access_denied` | Add your email as a test user in the consent screen |
| `invalid_scope` | Enable the required APIs in your GCP project first |
""",
    },
    {
        "name": "skill_security_checklist.md",
        "content": r"""# Skill Security Checklist

Before installing any skill from ClawHub, run through this checklist:

## Pre-Installation

- [ ] Install `skill-vetter` first: `clawhub install skill-vetter`
- [ ] Run the vetter: `openclaw vet <skill-name>`
- [ ] Check the skill's VirusTotal badge (should be **Benign**)
- [ ] Review the skill's permissions in `~/.openclaw/skills/<name>/manifest.yaml`

## Permission Levels

| Level | Access | Example Skills |
|-------|--------|---------------|
| 🟢 Read-only | Can read data, no writes | `summarize`, `weather` |
| 🟡 Read-write | Can create/modify data | `notion`, `todoist` |
| 🔴 Full access | System-level operations | `agent-browser`, `shell` |

## Post-Installation Audit

```bash
# List all installed skills and their permission levels
openclaw skills list --verbose

# Review what APIs a skill accesses
openclaw skills inspect <skill-name> --permissions
```
""",
    },
    {
        "name": "vertex_ai_configuration.md",
        "content": r"""# Vertex AI Configuration for OpenClaw

## Model Selection

Based on your interview, we recommend:

| Use Case | Model | Why |
|----------|-------|-----|
| General chat | `gemini-2.5-pro` | Best balance of speed and quality |
| Summarization | `gemini-2.5-flash` | Fast, cost-effective for bulk processing |
| Code generation | `gemini-2.5-pro` | Strong reasoning for technical tasks |

## Configuration

```yaml
# ~/.openclaw/config.yaml
provider:
  name: vertex-ai
  project: restaurant-ai-prod
  region: us-central1
  models:
    default: gemini-2.5-pro
    fast: gemini-2.5-flash
  safety:
    block_threshold: BLOCK_MEDIUM_AND_ABOVE
```

## Cost Estimation

For a restaurant business with ~50 queries/day:

| Model | Est. Monthly Cost |
|-------|------------------|
| gemini-2.5-pro | ~$15-25 |
| gemini-2.5-flash | ~$3-8 |
| **Total estimate** | **~$20-35/mo** |
""",
    },
]

MOCK_PROMPTS = r"""# Prompts to Send

> Copy and paste these prompts into your OpenClaw instance after setup to initialize it with your preferences.

---

## Prompt 1: Set Your Identity & Personality

```
You are RestaurantConcierge, a professional AI assistant for Alex who manages a chain of 3 Italian restaurants in San Francisco. Your communication style is:

- Professional but warm, like a trusted restaurant manager
- Concise during busy hours (lunch 11am-2pm, dinner 5pm-10pm)
- More detailed and conversational outside rush hours
- Always prioritize food safety and health code compliance in any advice
- Use restaurant industry terminology naturally
```

## Prompt 2: Business Context

```
Here is my business context. Remember this for all future interactions:

- **Business:** 3 Italian restaurants — "Bella Vista" (Financial District), "Casa Nostra" (Marina), "Il Giardino" (North Beach)
- **Staff:** ~45 total employees across all locations
- **Suppliers:** Sysco (general), local farms for produce (bi-weekly), wine distributor (monthly)
- **Peak concerns:** Inventory management, staff scheduling, supplier coordination, health inspections
- **Tools I use daily:** Google Calendar, Gmail, Notion (SOPs), Google Sheets (inventory), Slack (team chat)
```

## Prompt 3: Daily Briefing Setup

```
Every morning at 7:00 AM, prepare a daily briefing that includes:

1. Today's reservations across all 3 locations
2. Any supplier deliveries expected today
3. Staff schedule highlights (who's on, any callouts)
4. Weather forecast (affects outdoor seating at Il Giardino)
5. Any urgent emails from the last 12 hours
6. Inventory alerts (items below reorder threshold)

Format it as a clean summary I can read in under 2 minutes.
```

## Prompt 4: Menu Intelligence

```
I'm uploading our current seasonal menu. For each dish, track:
- Ingredient costs and margin
- Customer feedback trends (from review platforms)
- Seasonal availability of key ingredients
- Suggested price adjustments based on food costs

Alert me when any dish drops below 65% margin or when a key ingredient price spikes >15%.
```

---

*Send these prompts in order after completing the setup guide steps.*
"""


# ========================================
# Request Models
# ========================================

class FormatRequest(BaseModel):
    transcript: str


class GenerateGuideRequest(BaseModel):
    formatted_transcript: str


# ========================================
# Endpoints
# ========================================

@app.post("/webhook")
async def vapi_webhook(request: Request):
    """VAPI server URL — receives transcript events, function-call requests,
    and end-of-call reports.

    Requires VAPI Private Key + Server URL configured in VAPI dashboard.
    """
    body = await request.json()
    message = body.get("message", {})
    msg_type = message.get("type", "unknown")

    logger.info(f"[WEBHOOK] Received event: {msg_type}")

    if msg_type == "transcript":
        transcript = message.get("transcript", "")
        role = message.get("role", "unknown")
        logger.info(f"[WEBHOOK] {role}: {transcript}")

    elif msg_type == "function-call":
        fn_name = message.get("functionCall", {}).get("name", "unknown")
        logger.info(f"[WEBHOOK] Function call: {fn_name}")
        return {"results": [{"result": "Function not implemented"}]}

    elif msg_type == "end-of-call-report":
        artifact = message.get("artifact", {})
        transcript = artifact.get("transcript", "")
        logger.info(f"[WEBHOOK] End of call — transcript length: {len(transcript)} chars")

        # Trigger formatter → guide generation pipeline
        try:
            formatted = await format_transcript(transcript)
            result = await generate_guide(formatted)
            guide_store[result["guide_id"]] = result
            logger.info(f"[WEBHOOK] Guide generated: {result['guide_id']}")
        except Exception as e:
            logger.error(f"[WEBHOOK] Pipeline failed: {e}")

    return {"ok": True}


@app.post("/format")
async def format_endpoint(req: FormatRequest):
    """Triggers the Interview Formatter on a transcript.

    Called by the frontend after a VAPI call ends (frontend-driven fallback),
    or triggered internally after webhook end-of-call-report.
    """
    logger.info(f"[FORMAT] Received transcript ({len(req.transcript)} chars)")
    formatted = await format_transcript(req.transcript)
    return {"formatted": formatted}


@app.post("/generate-guide")
async def generate_guide_endpoint(req: GenerateGuideRequest):
    """Triggers Phase 2: Setup Guide Creation Agent via RocketRide pipeline.

    Runs 3 sequential LLM calls (main guide, reference docs, prompts)
    and returns the assembled result.
    """
    logger.info(f"[GUIDE] Received formatted transcript ({len(req.formatted_transcript)} chars)")
    result = await generate_guide(req.formatted_transcript)
    guide_store[result["guide_id"]] = result
    return result


@app.get("/mock-generate")
async def mock_generate():
    """Returns a realistic demo guide for UI testing — no Vapi or RocketRide needed."""
    logger.info("[MOCK] Serving demo guide")
    return {
        "guide_id": "demo-0001",
        "status": "complete",
        "message": "Demo guide generated successfully.",
        "outputs": {
            "setup_guide": MOCK_SETUP_GUIDE,
            "reference_documents": MOCK_REFERENCE_DOCS,
            "prompts_to_send": MOCK_PROMPTS,
        },
    }


@app.get("/guide/{guide_id}")
async def get_guide(guide_id: str):
    """Retrieve generated output (guide + reference docs + prompts).

    Returns the guide from the in-memory store, or a not_found status.
    """
    if guide_id in guide_store:
        return guide_store[guide_id]
    return {
        "guide_id": guide_id,
        "status": "not_found",
        "message": "Guide not found. It may still be generating or the ID is invalid.",
    }


# ========================================
# Static File Serving (Frontend Build)
# ========================================

FRONTEND_DIST = os.path.join(os.path.dirname(__file__), "../frontend/dist")
PORT = int(os.environ.get("PORT", "8000"))

if os.path.isdir(FRONTEND_DIST):
    app.mount("/", StaticFiles(directory=FRONTEND_DIST, html=True), name="static")
    logger.info(f"Serving static files from: {FRONTEND_DIST}")
else:
    logger.info(f"Frontend build not found at {FRONTEND_DIST}")
    logger.info("Run 'npm run build' in the frontend directory for production serving.")

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=PORT)
